server:
  port: 56085
  servlet:
    context‐path: /sailing
ali:
  config:
    regionid: C3bbEZQRCOugEqVAEFtvJi3gpHW+W1UR
    accesskeyid: /cXWYT90JZXh8AryoWIgb6oxFP6HG3KZvi0R9APHS28=
    accesssecret: q/Okhjof8+IT4FaBemMYAtTs8hjfIBcji2O5jLoMNKwb5xZAn/zMvw==
  mobilemsg:
    signName: sngphVa8UO/2wJOg9JO89Aaf3sAtCzktprAb2r1U8SY=
    templateCode: cpl+URAm3kq8MoLDU7qpSc/8IpAtnCO1
    effectiveTime: 5 # 有效期5分钟
    
spring:
  application:
    name: sms-server
  redis:
    host: 192.168.199.106
    port: 6380
    password: 123456
    timeout: 10000

logging:
  config: classpath:log4j2.xml


