server:
  port: 56085
  servlet:
    context‐path: /sailing
ali:
  config:
    regionid: 
    accesskeyid: 
    accesssecret: 
  mobilemsg:
    signName: 
    templateCode: 
    effectiveTime: 5 # 有效期5分钟
    
spring:
  application:
    name: sms-server
  redis:
    host: 192.168.199.106
    port: 6380
    password: 123456
    timeout: 10000

logging:
  config: classpath:log4j2.xml


